// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BackBar: typeof import('./src/components/BackBar.vue')['default']
    BottomBanner: typeof import('./src/components/home/BottomBanner.vue')['default']
    CardDetail: typeof import('./src/components/grocery/cardDetail.vue')['default']
    FootTabBar: typeof import('./src/components/FootTabBar.vue')['default']
    Gift: typeof import('./src/components/center/Gift.vue')['default']
    GroCardDetail: typeof import('./src/components/grocery/groCardDetail.vue')['default']
    GroDetail: typeof import('./src/components/grocery/groDetail.vue')['default']
    GroupPurchase: typeof import('./src/components/home/GroupPurchase.vue')['default']
    HotPro: typeof import('./src/components/grocery/HotPro.vue')['default']
    List01: typeof import('./src/components/List01.vue')['default']
    MemberShipCard: typeof import('./src/components/home/MemberShipCard.vue')['default']
    NewPro: typeof import('./src/components/grocery/NewPro.vue')['default']
    NewsCard: typeof import('./src/components/grocery/NewsCard.vue')['default']
    NewTeaCreator: typeof import('./src/components/home/NewTeaCreator.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StudentCard: typeof import('./src/components/home/StudentCard.vue')['default']
    TeaParty: typeof import('./src/components/home/TeaParty.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanField: typeof import('vant/es')['Field']
    VanForm: typeof import('vant/es')['Form']
    VanGrid: typeof import('vant/es')['Grid']
    VanGridItem: typeof import('vant/es')['GridItem']
    VanIcon: typeof import('vant/es')['Icon']
    VanImage: typeof import('vant/es')['Image']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanSidebar: typeof import('vant/es')['Sidebar']
    VanSidebarItem: typeof import('vant/es')['SidebarItem']
    VanSwipe: typeof import('vant/es')['Swipe']
    VanSwipeItem: typeof import('vant/es')['SwipeItem']
    VanTab: typeof import('vant/es')['Tab']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
    VanTabs: typeof import('vant/es')['Tabs']
    Vip: typeof import('./src/components/center/Vip.vue')['default']
  }
}
